[profile.default]
src = "src"
out = "out"
libs = ["lib"]


[dependencies]
openzeppelin-contracts = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts", tag = "v4.9.2" }
forge-std = { git = "https://github.com/foundry-rs/forge-std", tag = "v1.6.0" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
